### ISSUE TITLE
fjage.py causes huge logs to be built up if no remote available

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage#44] opened 2018-07-22 01:30 UTC
If fjage.py had been connected to a remote and the remote gets disconnected (but fjage.py is still running like in an jupyter notebook) it generates gigantic logs (16GB) if not stopped.

```
1531907761.068|DEBUG|__init__.py@172:__recv_proc|192.168.2.14:1100 <<<
1531907761.068|CRITICAL|__init__.py@176:__recv_proc|Exception: Expecting value: line 1 column 1 (char 0)
1531907761.068|CRITICAL|__init__.py@170:__recv_proc|Exception: Socket Closed
1531907761.068|DEBUG|__init__.py@172:__recv_proc|192.168.2.14:1100 <<<
1531907761.068|CRITICAL|__init__.py@176:__recv_proc|Exception: Expecting value: line 1 column 1 (char 0)
1531907761.068|CRITICAL|__init__.py@170:__recv_proc|Exception: Socket Closed
1531907761.068|DEBUG|__init__.py@172:__recv_proc|192.168.2.14:1100 <<<
1531907761.068|CRITICAL|__init__.py@176:__recv_proc|Exception: Expecting value: line 1 column 1 (char 0)
1531907761.068|CRITICAL|__init__.py@170:__recv_proc|Exception: Socket Closed
1531907761.068|DEBUG|__init__.py@172:__recv_proc|192.168.2.14:1100 <<<
```

https://github.com/org-arl/fjage/blob/master/src/main/python/fjagepy/org_arl_fjage_remote/__init__.py#L166

**Comment by prasadtiru** [comment] 2018-07-22 01:34
Disabled the logging in 312fc30b857bc81bdc239ae2b3b4eb3687d64921 since it was only needed for debugging purpose and not needed in the production version.

**Comment by notthetup** [comment] 2018-07-23 03:06
@prasadtiru This will remove the `DEBUG` level logs, but there are many at `CRITICAL` level as well.

I can see two issues.

1. We shouldn't try to `self._parse_dispatch(rmsg, q)` if `if not rmsg`. So I think we're missing a `continue` or `break` on after Line 170. This is causing the exception "Exception: Expecting value: line 1 column 1 (char 0)"

2. On Java side it seems we `break` out of the while loop and close the connection if the line read is null.

https://github.com/org-arl/fjage/blob/master/src/main/java/org/arl/fjage/remote/ConnectionHandler.java#L47

Not sure if the `readLine()` on `BufferedReader ` behaves similarly to `socket_file.readline()` in Python. 

Cos if the remote indeed drops the connection, does the `readLine()` on `BufferedReader ` return `null` or does it block indefinitely?

Ideally, we'd like the Python behaviour to follow the Java behaviour.

**Comment by prasadtiru** [comment] 2018-07-23 06:47
Fixed the cause for the exception in 16bf56a859b8ad521cc85e492c2b05e3c4a4256c . This issue of logs build up when no remote available is fixed. 

Although, the Java behavior is such that the gateway connection automatically reconnects the closed connection when the unet starts running again. We need to do discuss on how we can do the same for python gateway.

**Comment by mchitre** [comment] 2018-11-12 08:47
@prasadtiru fixed or needs to still be kept open?

**Comment by prasadtiru** [comment] 2018-11-12 10:48
Closing this issue and created another feature request #51 for following the same behavior as java when the remote connection is dropped.

**Closed by prasadtiru** 2018-11-12 10:48 UTC
Labels: bug, python
