### ISSUE TITLE
WebShell does strange things with the first line

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage#94] opened 2019-10-03 05:20 UTC
The first line after a reboot (before pressing `Return`), in the WebShell tends to behave strangely.

- It doesn't like backspaces.
- If copying large strings, the formating goes haywire.

**Comment by mchitre** [comment] 2019-10-05 16:09
Was a hard one to track down. Turns out that the default terminal state sends ANSI sequences for keystrokes of the kind `ESC[D`, whereas readline wants them as `ESC OD` (application mode). We now fix this by having `TcpHubConnector` put in the right escape sequences as part of the terminal negotiation to setup `telnet` correctly, and `shell/index.html` sending this escape sequence to `hterm` to set it up correctly.

**Comment by notthetup** [comment] 2019-10-06 09:51
OMG!! 😱

**Comment by manuignatius** [comment] 2019-10-10 09:07
Pressing up or down arrows in terminal gives strange characters.
![Screenshot 2019-10-10 at 5 07 18 PM](https://user-images.githubusercontent.com/4144181/66554980-7bfc8a00-eb80-11e9-9c2f-1a7dc3a214b7.png)

**Comment by mchitre** [comment] 2019-10-11 03:18
@manuignatius I can't reproduce your problem. Test setup:
```
> ver
fjage-1.6.2-SNAPSHOT/698c4209/11-10-2019_10:58:57
node-3.0.0/bcc9bf66/11-10-2019_11:12:53
phy-3.0.0/bcc9bf66/11-10-2019_11:12:53
UnetStack/Unet audio
unetaudio
```

I suspect you have the wrong version of the `index.html` in your browser cache. Try this:
1. Make sure you're using the latest `fjage-1.6.2-SNAPSHOT.jar`. For this best to do a `gradle --refresh-dependencies`.
2. Clear browser cache and restart browser.
3. Then connect to the terminal and see if problem persists.

If it does, check:
```
> nc localhost 8080     # or whatever your IP and port is
GET /fjage/shell/index.html HTTP/1.0
```
In the response, check if you find the line:
```
io.print('\x1b[?1h\x1b=\x1b[?2004h')
```
If you don't, its a problem of wrong version of fjage or browser cache. If you find it, and still problem persists, please provide exact steps to reproduce it.

**Comment by mchitre** [comment] 2019-10-15 14:42
This is still a problem. On OS X, this fix works. But on modem (Linux?), this doesn't. Removing the `io.print`works on modem!

**Comment by mchitre** [comment] 2019-10-15 16:16
Fixed by forcing terminal to be `xterm-noapp` and removing hack to set application mode cursor keys. So, now only paste bracketing is hacked in.

**Comment by mchitre** [comment] 2019-10-15 16:16
@manuignatius / @notthetup need help testing on modem.

**Comment by manuignatius** [comment] 2019-10-17 00:25
Tested and the issue is not there anymore.

**Closed by manuignatius** 2019-10-17 00:25 UTC
Labels: bug
