### ISSUE TITLE
Can't open Fjage shell by ./fjage.sh

### ISSUE THREAD

**Issue by verma-ajey** [org-arl/fjage#70] opened 2019-05-09 10:53 UTC
When I run fjage.sh script, it won't direct me to '>' prompt, rather following error was logged in in log files every time I try to execute it.

1557382840953|INFO|org.arl.fjage.shell.GroovyBoot@1:main|fjage Build: fjage-1.5.1/25-01-2019_16:23:51
1557382841380|INFO|org.arl.fjage.shell.GroovyBoot@1:main|Running etc/initrc.groovy
1557382841453|WARNING|org.arl.fjage.shell.GroovyScriptEngine@1:error|Groovy script execution failed

java.lang.NoClassDefFoundError: org/eclipse/jetty/websocket/servlet/WebSocketCreator
Stack trace: ...
   org.arl.fjage.shell.GroovyScriptEngine.exec(GroovyScriptEngine.java:197)
   org.arl.fjage.shell.GroovyBoot.main(GroovyBoot.java:95)

I even included **websocket-servlet-9.1.0.m0.jar** file to build/libs/ to provide WebSocketCreator class reference. 

[log-7.txt](https://github.com/org-arl/fjage/files/3161715/log-7.txt)

**Comment by mchitre** [comment] 2019-05-12 15:54
Are you trying to build from the source repo or using the binary release on Maven? If you're building from the source repo, did you build using `gradle` and let gradle download the dependencies?

**Comment by mchitre** [comment] 2019-07-24 13:54
Closing this due to lack of information and ability to reproduce.

**Closed by mchitre** 2019-07-24 13:54 UTC
Labels: unconfirmed
